language: node_js
node_js:
  - "4"
  - "5"
  - "6"
before_script:
  - npm install
  - npm install codecov
script:
  - npm run test
  - npm run build
after_script:
  - cat coverage/*/lcov.info | ./node_modules/codecov/bin/codecov
